export const types = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCSES: 'LOGIN_SUCCSES',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCSES: 'LOGOUT_SUCCSES',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
};
